#postgre db
spring:
  datasource:
    postgresql:
      url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/
      username: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:example}
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
