#postgre db
spring:
  datasource:
    postgresql:
      url: jdbc:postgresql://localhost:5432/postgres
      username: lammai
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

#second db
#spring.datasource.mysql.url= jdbc:postgresql://localhost:5432/postgres
#spring.datasource.mysql.username= lammai
